<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Authors>Rene Peuser</Authors>
        <Company>Rene Peuser Softwaresolutions</Company>
        <Description>WIP - This simple SDK to parse solution, projects and c# files</Description>
        <Copyright>Copyright 2022 (c) Rene Peuser. All rights reserved.</Copyright>
        <PackageProjectUrl>https://renepeuser.visualstudio.com/Solution.Parser</PackageProjectUrl>
        <RepositoryUrl>https://renepeuser.visualstudio.com/Solution.Parser</RepositoryUrl>
        <PackageReleaseNotes>Upgrade .Net 8</PackageReleaseNotes>
        <PackageTags>C#;Solution;Project;XAML;SyntaxTree;Syntax</PackageTags>
        <PackageId>Solution.Parser</PackageId>
        <OutputType>Library</OutputType>
        <AssemblyName>Solution.Parser</AssemblyName>
        <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
        <PackageLicenseFile>License.txt</PackageLicenseFile>
    </PropertyGroup>

    <!--Property group settings for source link !-->
    <PropertyGroup>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <DebugType>embedded</DebugType>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <DocumentationFile>.\Solution.Parser.xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NuGet.Configuration" Version="6.6.1" />
        <PackageReference Include="NuGet.Versioning" Version="6.6.1" />
        <PackageReference Include="Argument.Check" Version="3.0.1" />
        <PackageReference Include="Extensions.Pack" Version="3.0.3" />
        <PackageReference Include="FileSystem.Abstraction" Version="0.1.2" />
        <PackageReference Include="GitVersion.MsBuild" Version="5.12.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Build" Version="17.6.3" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.6.0" />
        <PackageReference Include="Microsoft.SourceLink.AzureRepos.Git" Version="1.1.1" PrivateAssets="All" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\License.txt">
            <Pack>True</Pack>
            <PackagePath></PackagePath>
        </None>
        <None Include="..\..\README.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>

</Project>
