<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Extensions.Pack" Version="7.0.0-alpha.28" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
        <PackageReference Include="MSTest.TestAdapter" Version="4.1.0" />
        <PackageReference Include="MSTest.TestFramework" Version="4.1.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Solution.Parser\Solution.Parser.csproj" />
    </ItemGroup>

</Project>
